### ISSUE TITLE
Runtime error on cuda

### ISSUE THREAD

**Issue by SohamMazumder** [shaoxiongji/federated-learning#4]
`bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)

cuda:0

CNNMnist(

(conv1): Conv2d(1, 10, kernel_size=(5, 5), stride=(1, 1))

(conv2): Conv2d(10, 20, kernel_size=(5, 5), stride=(1, 1))

(conv2_drop): Dropout2d(p=0.5)

(fc1): Linear(in_features=320, out_features=50, bias=True)

(fc2): Linear(in_features=50, out_features=10, bias=True)

)

/opt/conda/lib/python3.6/site-packages/torchvision/datasets/mnist.py:43: UserWarning: train_labels has been renamed targets

warnings.warn("train_labels has been renamed targets")

Traceback (most recent call last):

File "main_fed.py", line 113, in <module>

w, loss = local.train(net=copy.deepcopy(net_glob).to(args.device))

File "/code/models/Update.py", line 48, in train

loss = self.loss_func(log_probs, labels)

File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__

result = self.forward(*input, **kwargs)

File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 904, in forward

ignore_index=self.ignore_index, reduction=self.reduction)

File "/opt/conda/lib/python3.6/site-packages/torch/nn/functional.py", line 1970, in cross_entropy

return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)

File "/opt/conda/lib/python3.6/site-packages/torch/nn/functional.py", line 1790, in nll_loss

ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)

RuntimeError: Expected object of backend CUDA but got backend CPU for argument  'weight'`

I get the above error, only when trying to run it on CUDA.

**Comment by shaoxiongji** [comment]
Sorry for the delay. This issue should be fixed after previous updating.
